name: IPTV Daily Update

on:
  schedule:
    - cron: '0 0,12 * * *'  # UTC时间0点和12点（对应北京时间8点和20点）
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install aiohttp

    - name: Run scraping script
      run: python .github/workflows/iptv.py

    - name: Capture execution time
      id: time
      run: |
        TZ="Asia/Shanghai"
        echo "exec_time=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_OUTPUT

    - name: Update README
      run: |
        sed -i "s/最后运行时间：.*/最后运行时间：${{ steps.time.outputs.exec_time }}/g" README.md
        sed -i "s|文件链接：.*|文件链接：https://github.com/${{ github.repository }}/raw/main/best_sorted.m3u|g" README.md

    - name: Commit changes
      env:
        REPO_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin $REPO_URL
        git add README.md best_sorted.m3u
        git commit -m "自动更新：${{ steps.time.outputs.exec_time }}"
        git push origin main
